"""
network_isolation.py  —  Egress allow-list and network policy generator
AI Fortress · Chapter 4 · Code Sample 4.A

Generates network restriction artefacts for training jobs:

  1. iptables rules  — per-job egress allow-list for bare-metal / VM environments
  2. nftables rules  — modern alternative to iptables
  3. Kubernetes NetworkPolicy manifest — restricts pod egress to declared endpoints
  4. Docker --network run flags  — for single-container training jobs
  5. Audit log verifier  — scans system network audit logs for unexpected connections
     that occurred during a completed training job (post-hoc analysis)

Principle: deny-all egress by default, then allow only:
  - Dataset bucket endpoints (S3, GCS, Azure Blob)
  - Model registry (MLflow, W&B, Vertex)
  - Package mirrors (PyPI, conda)
  - Internal secrets backend (Vault, AWS Secrets Manager)
"""
from __future__ import annotations

import json
import re
import socket
from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class AllowedEndpoint:
    host:        str
    port:        int
    protocol:    str = "tcp"    # tcp | udp
    description: str = ""

    def resolve_ip(self) -> Optional[str]:
        try:
            return socket.gethostbyname(self.host)
        except socket.gaierror:
            return None


@dataclass
class NetworkPolicy:
    job_id:    str
    endpoints: List[AllowedEndpoint] = field(default_factory=list)

    def add(self, host: str, port: int, protocol: str = "tcp", description: str = "") -> None:
        self.endpoints.append(AllowedEndpoint(host, port, protocol, description))


# ── Pre-built endpoint sets ───────────────────────────────────────────────────

def aws_endpoints() -> List[AllowedEndpoint]:
    return [
        AllowedEndpoint("s3.amazonaws.com",               443, description="S3 data"),
        AllowedEndpoint("secretsmanager.amazonaws.com",   443, description="Secrets Manager"),
        AllowedEndpoint("sts.amazonaws.com",              443, description="STS tokens"),
        AllowedEndpoint("ecr.amazonaws.com",              443, description="Container registry"),
    ]

def pypi_endpoints() -> List[AllowedEndpoint]:
    return [
        AllowedEndpoint("pypi.org",          443, description="PyPI"),
        AllowedEndpoint("files.pythonhosted.org", 443, description="PyPI files"),
    ]

def wandb_endpoints() -> List[AllowedEndpoint]:
    return [
        AllowedEndpoint("api.wandb.ai",  443, description="W&B metrics"),
        AllowedEndpoint("wandb.ai",      443, description="W&B UI"),
    ]


# ── Generators ────────────────────────────────────────────────────────────────

class NetworkPolicyGenerator:
    """Generates network restriction artefacts from a NetworkPolicy definition."""

    def iptables_rules(self, policy: NetworkPolicy) -> str:
        """
        Generate iptables rules for a training job.
        Apply with: iptables-restore < rules.txt
        Intended for bare-metal or VM-based training.
        """
        lines = [
            f"# AI Fortress — Network isolation rules for job: {policy.job_id}",
            "# Generated by network_isolation.py",
            "*filter",
            ":INPUT ACCEPT [0:0]",
            ":FORWARD DROP [0:0]",
            ":OUTPUT DROP [0:0]",   # default deny all egress
            "",
            "# Allow loopback",
            "-A OUTPUT -o lo -j ACCEPT",
            "",
            "# Allow established/related connections",
            "-A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT",
            "",
            "# Allow DNS (needed to resolve allow-list hostnames)",
            "-A OUTPUT -p udp --dport 53 -j ACCEPT",
            "-A OUTPUT -p tcp --dport 53 -j ACCEPT",
            "",
            "# Allow-list endpoints:",
        ]
        for ep in policy.endpoints:
            comment = f"# {ep.description}" if ep.description else ""
            lines.append(comment)
            lines.append(
                f"-A OUTPUT -p {ep.protocol} -d {ep.host} --dport {ep.port} -j ACCEPT"
            )
        lines += [
            "",
            "# Log and drop everything else",
            "-A OUTPUT -j LOG --log-prefix '[AI-FORTRESS-BLOCKED] ' --log-level 4",
            "-A OUTPUT -j DROP",
            "COMMIT",
        ]
        return "\n".join(lines)

    def nftables_rules(self, policy: NetworkPolicy) -> str:
        """Generate nftables ruleset for a training job."""
        allow_stmts = []
        for ep in policy.endpoints:
            allow_stmts.append(
                f'        ip daddr {ep.host} tcp dport {ep.port} accept'
                f'  # {ep.description}'
            )
        allow_block = "\n".join(allow_stmts)

        return f"""#!/usr/sbin/nft -f
# AI Fortress — nftables isolation for job: {policy.job_id}

table inet ai_fortress_training {{
    chain output {{
        type filter hook output priority 0; policy drop;

        # Loopback
        oif lo accept

        # Established connections
        ct state established,related accept

        # DNS
        udp dport 53 accept
        tcp dport 53 accept

        # Allow-list:
{allow_block}

        # Log blocked
        log prefix "[AI-FORTRESS-BLOCKED] " flags all
    }}
}}
"""

    def kubernetes_network_policy(self, policy: NetworkPolicy, namespace: str = "ml-training") -> dict:
        """
        Generate a Kubernetes NetworkPolicy manifest (YAML-serialisable dict).
        Apply with: kubectl apply -f network-policy.yaml
        """
        egress_rules = []

        # DNS rule
        egress_rules.append({
            "ports": [{"port": 53, "protocol": "UDP"}, {"port": 53, "protocol": "TCP"}]
        })

        # Per-endpoint rules
        for ep in policy.endpoints:
            egress_rules.append({
                "to": [{"ipBlock": {"cidr": "0.0.0.0/0"}}],
                "ports": [{"port": ep.port, "protocol": ep.protocol.upper()}],
            })

        return {
            "apiVersion": "networking.k8s.io/v1",
            "kind": "NetworkPolicy",
            "metadata": {
                "name": f"training-isolation-{policy.job_id}",
                "namespace": namespace,
                "labels": {"app": "ai-fortress", "job-id": policy.job_id},
            },
            "spec": {
                "podSelector": {"matchLabels": {"job-id": policy.job_id}},
                "policyTypes": ["Egress"],
                "egress": egress_rules,
            },
        }

    def docker_network_flags(self, policy: NetworkPolicy) -> str:
        """
        Return Docker run flags to restrict the container to a custom bridge network.
        The caller must first create the network:
          docker network create --internal training-net-<job_id>
        Then add the allow-listed IPs as host aliases.
        """
        lines = [
            f"# Create isolated network (blocks external by default with --internal):",
            f"docker network create --internal training-net-{policy.job_id}",
            f"",
            f"# Run training container on the isolated network:",
            f"docker run \\",
            f"  --network training-net-{policy.job_id} \\",
        ]
        for ep in policy.endpoints:
            ip = ep.resolve_ip() or "UNRESOLVED"
            lines.append(f"  --add-host {ep.host}:{ip} \\  # {ep.description}")
        lines.append("  <your-training-image>")
        return "\n".join(lines)


class EgressAuditVerifier:
    """
    Post-hoc: scan a network audit log for unexpected egress connections
    that occurred during a training job.
    """

    def __init__(self, policy: NetworkPolicy):
        self.policy = policy
        self._allowed_set = {
            (ep.host, ep.port) for ep in policy.endpoints
        }

    def verify_log(self, log_lines: List[str]) -> List[dict]:
        """
        Scan log lines for AI-FORTRESS-BLOCKED or similar deny-log entries.
        Returns list of unexpected connection attempt records.
        """
        blocked: List[dict] = []
        pattern = re.compile(
            r"\[AI-FORTRESS-BLOCKED\].*DST=(?P<dst>\S+).*DPT=(?P<dpt>\d+)"
        )
        for line in log_lines:
            m = pattern.search(line)
            if m:
                blocked.append({
                    "dst":  m.group("dst"),
                    "port": int(m.group("dpt")),
                    "raw":  line.strip(),
                })
        return blocked
