"""
format_preserving.py  —  Format-preserving fake-value substitution
AI Fortress · Chapter 2 · Code Sample 2.B

Replaces PII fields with syntactically valid fake values generated by Faker.
Unlike pseudonymisation, the output values are NOT deterministic per input —
they are random each time.  Use this for test datasets that must pass
downstream format validation (e.g. email regex checks, phone length checks).
"""
from __future__ import annotations

import random
import re
from typing import Callable, Dict
import pandas as pd
from faker import Faker
from pii_detector import PIIType

_faker = Faker("en_GB")
_faker_us = Faker("en_US")

# Generators per PII type
_GENERATORS: Dict[PIIType, Callable[[], str]] = {
    PIIType.EMAIL:        lambda: _faker.email(),
    PIIType.PHONE_UK:     lambda: _faker.phone_number(),
    PIIType.PHONE_US:     lambda: _faker_us.phone_number(),
    PIIType.SSN:          lambda: _faker_us.ssn(),
    PIIType.CREDIT_CARD:  lambda: _faker.credit_card_number(),
    PIIType.IP_ADDRESS:   lambda: _faker.ipv4_private(),
    PIIType.DATE_OF_BIRTH: lambda: _faker.date_of_birth(minimum_age=18, maximum_age=90).isoformat(),
    PIIType.POSTCODE_UK:  lambda: _faker.postcode(),
    PIIType.POSTCODE_US:  lambda: _faker_us.zipcode(),
    PIIType.IBAN:         lambda: _faker.iban(),
    PIIType.NHS_NUMBER:   lambda: " ".join([str(random.randint(100,999)) for _ in range(3)]),
    PIIType.NPI_NUMBER:   lambda: str(random.randint(1000000000, 9999999999)),
    PIIType.PASSPORT_UK:  lambda: str(random.randint(100000000, 999999999)),
}


def fake_value(pii_type: PIIType) -> str:
    """Generate a single format-preserving fake value for a PII type."""
    gen = _GENERATORS.get(pii_type)
    return gen() if gen else "[FAKE]"


def replace_pii_in_text(text: str, pii_type: PIIType) -> str:
    """Replace all occurrences of a PII type in a text string with fake values."""
    from pii_detector import _PATTERNS
    pattern = _PATTERNS.get(pii_type)
    if not pattern:
        return text
    return pattern.sub(lambda _: fake_value(pii_type), text)


def anonymise_dataframe(
    df:                  pd.DataFrame,
    column_pii_map:      Dict[str, PIIType],
) -> pd.DataFrame:
    """
    Replace PII in specified columns with format-preserving fake values.

    Parameters
    ----------
    column_pii_map : mapping of column name → PIIType
        e.g. {"email": PIIType.EMAIL, "phone": PIIType.PHONE_UK}
    """
    out = df.copy()
    for col, pii_type in column_pii_map.items():
        if col not in out.columns:
            continue
        gen = _GENERATORS.get(pii_type, lambda: "[FAKE]")
        out[col] = out[col].apply(lambda v: gen() if pd.notna(v) and str(v).strip() else v)
    return out
